# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.IntegerField()),
                ('CarId', models.IntegerField()),
                ('ApiId', models.IntegerField()),
                ('ApiName', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectId', models.IntegerField()),
                ('CarId', models.IntegerField()),
                ('CartName', models.CharField(max_length=225)),
            ],
        ),
    ]
